import "./globals.css";
import Footer from "../components/common/Footer";
import MountWrapper from "../components/common/MountWrapper";
import {Toaster} from "@/components/ui/sonner";
import {categories} from "@/utils/api/home/fetchhome";
import HeaderWrapper from "@/components/common/HeaderWrapper";
import {getAuthToken} from "@/utils/checkCookies";
export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};
export default async function RootLayout({children}: {children: React.ReactNode}) {
 const token = await getAuthToken();
 const categorie = await categories();
 return (
  <html dir="rtl" lang="fa">
   <head>
    <link rel="preload" as="image" href="/pages/home/slide1.webp" />
   </head>
   <body className={`font-sansv flex flex-col min-h-dvh`}>
    <HeaderWrapper isLogin={!!token} categorie={categorie} token={token ?? ""} />
    <main className="flex flex-grow w-full">
     <MountWrapper>{children}</MountWrapper>
    </main>
    <Toaster />
    <Footer />
   </body>
  </html>
 );
}
