import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "../components/common/Header";
import Footer from "../components/common/Footer";
import MountWrapper from "../components/common/MountWrapper";

const geistSans = Geist({
 variable: "--font-geist-sans",
 subsets: ["latin"],
});

const geistMono = Geist_Mono({
 variable: "--font-geist-mono",
 subsets: ["latin"],
});

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html dir="rtl" lang="fa">
   <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
    <Header />
    <main className="flex min-h-screen">
     <MountWrapper>{children}</MountWrapper>
    </main>
    <Footer />
   </body>
  </html>
 );
}
