import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Footer from "../components/common/Footer";
import MountWrapper from "../components/common/MountWrapper";
import {Toaster} from "@/components/ui/sonner";
import {categories} from "@/utils/fetchhome";
import HeaderWrapper from "@/components/common/HeaderWrapper";
import {getAuthToken} from "@/utils/checkCookies";

const geistSans = Geist({
 variable: "--font-geist-sans",
 subsets: ["latin"],
 display: "swap",
});

const geistMono = Geist_Mono({
 variable: "--font-geist-mono",
 subsets: ["latin"],
 display: "swap",
});

export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};
export default async function RootLayout({children}: {children: React.ReactNode}) {
 const token = await getAuthToken();
 const categorie = await categories();

 return (
  <html dir="rtl" lang="fa">
   <head>
    <link rel="preload" as="image" href="/pages/home/slide1.webp" />
   </head>
   <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-dvh`}>
    <HeaderWrapper isLogin={!!token} categorie={categorie} />
    <main className="flex flex-grow">
     <MountWrapper>{children}</MountWrapper>
    </main>
    <Toaster />
    <Footer />
   </body>
  </html>
 );
}
